config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'new_data', to: 'home#new_data'
  get 'instructions', to: 'home#instructions'
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :items, only: [:index]
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
  resources :users, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_item.rb
class CategoriesItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :items
  validates :name , presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  validates :content , :item, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :comments, dependent: :destroy
  validates :title , presence: true, uniqueness: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :user, optional: true
  validates :comment , presence: true
  before_save :duplicate_like 

  def duplicate_like
    !self.user_id.nil? && Like.where( user_id: self.user_id, comment_id: self.comment_id).any? ? throw(:abort) : ''
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < V1Controller

      def create
        @comment = Comment.new(comment_params)
        if @comment.save
          @status = :created
        else
          @status = :bad_request
        end
        render :create, status: @status
      end

      private
      def comment_params
        params.require(:comment)
              .permit(:content, :user_id, :item_id)
      end
    end
  end
end

app/controllers/api/v1/items_controller.rb
module Api
  module V1
    class ItemsController < V1Controller
      def index
        @items = Item.all
      end
    end
  end
end
  

app/controllers/api/v1/likes_controller.rb
module Api
  module V1
    class LikesController < V1Controller
      def create
        @like = Like.new(like_params)
        if @like.save
          @status = :created
        else
          @status = :bad_request
        end
        render status: @status
      end

      private
      def like_params
        params.require(:like)
              .permit(:comment_id, :user_id)
      end
    end
  end
end

app/controllers/api/v1/v1_controller.rb
module Api
  class V1::V1Controller < ApiController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  include ApplicationHelper
  
  def index
  end

  def new_data
  	get_data_json(params['url'])
    redirect_to root_path
  end
  
  def instructions
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end

  def create
    User.create(name: Faker::Name.name)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
  require 'uri'
  require 'net/http'
  require 'json'
  
  def get_data_json(url)
    url = url.gsub(" ","")
    escaped_address = URI.escape(url) 
    uri = URI.parse(url)

    if uri.kind_of?(URI::HTTP) or uri.kind_of?(URI::HTTPS)
      result = Net::HTTP.get_response(uri)
      if valid_json?(result.body)
        result = JSON.parse(result.body)
      else  
        return false  
      end
      if !result.nil? && !result['items'].nil? 
        result['items'].each do |item|
          i = Item.create(fecha: item['fecha'], title: item['title'], image: item['image'], content: item['content'], all_content: item['all_content'],  link: item['link'])
          !item['comments'].nil? ? Comment.create(content: item['comments'], item_id: i.id) : ''
          if !item['categories'].nil? 
            item['categories'].each do |cat| ## validar esto 
              c = Category.where(name: cat['name'] )
              if c.empty?
                c = Category.create(name: cat['name'], slug: cat['slug'])
                !i.errors.messages.any? ?  CategoriesItem.create( category_id: c.id, item_id: i.id) : ''       
              else
                !i.errors.messages.any? ?  CategoriesItem.create( category_id: c[0].id, item_id: i.id) : ''
              end
            end
          end
        end
      end
    end
  end

  def valid_json?(string)
    begin
      !!JSON.parse(string)
    rescue JSON::ParserError
      false
    end
  end
end

app/views/home/index.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="card">
    <img class="logo m-b-30" alt="Funx" src="<%= asset_path 'logo.png' %>" height="60">
    <p></p>
    <strong>Total items : </strong>
    <%= Item.all.size %>
    <p></p>
    <strong>Total categories : </strong>
    <%= Category.all.size %>
    <p></p>
    <strong>Total comments : </strong>
    <%= Comment.all.size %>
    <p></p>
    <strong>Total likes : </strong>
    <%= Like.all.size %>
    <p></p>
    <strong>Total Users : </strong>
    <%= User.all.size %>
    <p></p>
    <strong>Get data from : </strong> https://www.teleton.cl/feed/?json
    <p></p>
    <%= form_tag new_data_path, method: 'post' do |f| %>
      <div class="form-group">
      <label class="control-label text-left">Url</label>
      <%= text_field_tag :url, nil, :required => true, class: "form-control" , placeholder: "put a valid url" %>
      </div>
      <div class="form-actions">
      <%= submit_tag "Send", class: "btn btn-primary pull-left" %>
      </div>
    <% end %>
    <%= link_to "Create Random user", users_path, :method => :post, class: "btn btn-danger pull-left" %>
    <%= link_to "All users", users_path, class: "btn btn-success pull-left" %>
    <%= link_to "Instructions", instructions_path, class: "btn btn-warning pull-left" %>
    
  </div>
</div>

app/views/home/instructions.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="card">
    <img class="logo m-b-30" alt="Funx" src="<%= asset_path 'logo.png' %>" height="60">
    <center><h3>Instructions</h3></center> 
    Put a valid teleton url in the input url and then press Send to get items in to the system.
    <p></p>
    <strong>To list all items just use get to this url : </strong> http://localhost:3000/api/v1/items/
    <p></p>
    <strong>To create a comment use a post method to this url : </strong> http://localhost:3000/api/v1/comments/ . with content and item_id
    as minimum params add user_id to regiter author.
    <p></p>
    <strong>To create a like use a post method to this url : </strong> http://localhost:3000/api/v1/likes/ . with comment_id
    as minimum params add user_id to regiter author.
    <p></p>
    <%= link_to "Go to Home", root_path, class: "btn btn-success" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funx app</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<table class="table" id="users_datatable" data-source="<%= users_path(format: "json") %>">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>